### ISSUE TITLE
Feature request: close buffers matching regexp

### ISSUE THREAD

**Issue by pwntester** [kazhala/close-buffers.nvim#1]
Hi, thanks for the plugin, looks great!

would it be possible to implement a feature to close all buffers matching a specific pattern such as `octo://*` or `docker://*`?

thanks!

**Comment by kazhala** [comment]
Hi @pwntester ,

I've added support for regex and glob patterns when performing deletions.

```
# lua
require('close_buffers').delete({type = 'hidden', regex = '.*docker.*', force = true})
require('close_buffers').delete({type = 'hidden', glob = '*docker://*', force = true})

# vim
:BDelete! all regex=.*octo.*
:BDelete! all glob=*octo://*
```

Thanks,
Kevin

**Comment by pwntester** [comment]
Awesome, thanks!

**Comment by pwntester** [comment]
Im wondering if the `all` is superfluos though, perhaps it would be enough with:

```
:BDelete! regex=.*octo.*
:BDelete! glob=*octo://*
```

**Comment by kazhala** [comment]
I think you are correct, deletion type should be optional and just fall back to all if not provided.

I'll reopen it.

Thanks!

**Comment by kazhala** [comment]
You should be able to use glob and regex without specifying a type now.

Thanks,
Kevin
