### ISSUE TITLE
Go to previous buffer instead of the last when closing current.

### ISSUE THREAD

**Issue by aj3423** [kazhala/close-buffers.nvim#11]
It seems goes to last buffer instead of previous one, for example:

- 3 buffers in order:  A  B  C
- switch from A to C
- close current buffer C with `lua require("close_buffers").delete({ type = "this" })`
- it switches to B instead of A

Is it possible to switch back to A when C is closed? Because A is the buffer before it switched to C.

Thanks.

**Comment by letstakeawalk** [comment]
I know this is an old issue, but here's what you can do:
```lua
next_buffer_cmd = function()
    local bufs = vim.tbl_filter(function(b) return b.listed == 1 end, vim.fn.getbufinfo())
    table.sort(bufs, function(a, b) return a.lastused > b.lastused end)
    if #bufs > 1 then
        local most_recent = bufs[2].bufnr -- when num of wins > 2, unexpected result
        vim.api.nvim_win_set_buf(0, most_recent)
    end
end
```

As shown in your example, opening A, B and C in order, switching from A to C then `<cmd>BWipeout this<cr>` will open A.

Please note that this behaves unexpectedly when working with 2+ windows.

One useful built-in keymap for switching between two buffers (opening the previously edited file) is `<C-6>`(`<C-^>`). But this has two problems:

- Open A, B, C, `:bwipe` (B opens), then `<C-6>` errors as C is wiped out from the buffer list
- Open A, B, C, `:bdelete` (B opens), then `<C-6>` reopens C (not desirable)

So I wrote an improved version of `<C-6>` which will switch between B and A after `:bd` on C.
```lua
set("n", "<C-6>", function()
    local success, _ = pcall(vim.cmd.e, "#")  -- `:e #` == `<C-6>`
    if not success then
        local bufs = vim.tbl_filter(function(b) return b.listed == 1 end, vim.fn.getbufinfo())
        table.sort(bufs, function(a, b) return a.lastused > b.lastused end)
        if #bufs == 1 then
            vim.notify("No alternate file exists", vim.log.levels.WARN)
        else
            vim.api.nvim_win_set_buf(0, bufs[2].bufnr)
        end
    end
end, { desc = "Open recently edited buffer" })
```

I hope this helps

**Comment by aj3423** [comment]
@ryanbyon Thanks for the detailed explanation, I ended up using this plugin https://github.com/ojroques/nvim-bufdel, the config `next = 'alternate'` does exactly this.
